# you can override this default config file with the untracked config.local.yaml
speech_to_text:
  max_chunk_length_minutes: 4
  details_log: false

lm_studio:
  server_api_host: "127.0.0.1:1234"
  model: "bartowski/mistralai_Ministral-3-14B-Instruct-2512-GGUF"
  model_variant: "Q5_K_M"
  model_key: "mistralai_ministral-3-14b-instruct-2512"
  offload_gpu: true